name: 'Check History Action'
description: 'Compare commits with file Regex and shows status if it should run the check or not'
author: 'saurav0705'
inputs:
  GIT_TOKEN:
    required: false
    description: 'GITHUB TOKEN FOR THE REPO'
    default: ${{github.token}}
  UPLOAD:
    description: This is required to publish the successful sha to repo varaible
    required: false
    default: |
      key: ''
      retentionDays : 30
  CONFIG:
    required: true
    description: |
      // This is the config for the action it can take either file path or you can directly pass the config which follows the below structure
      ./.github/config.yml 
            OR
      disable: false // disables the check
      comment:
        disable: false // disables the PR comment
        retentionDays: 30 // artifact which contains the PR comment info if not given is set to 30 days
      checks:
        - key: name
          pattern:
            - PATH_1
            - PATH_2
          disbale: false // disable individual check
          disableInComment: false // does not post status in message
    default: ''

branding:
  icon: cloud-lightning
  color: blue
runs:
  using: 'node20'
  main: 'dist/index.js'
