name: Release

concurrency:
  group: release
  cancel-in-progress: false

on:
  workflow_dispatch:
    inputs:
      type:
        description: release type
        required: true
        type: choice
        default: patch
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn
      - name: bump version
        shell: bash
        run: npm version ${{inputs.type}}
      - name: Get Package version
        id: version
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: 'package.json'
          prop_path: 'version'
      - name: commit to main
        shell: bash
        env:
          CI_COMMIT_MESSAGE: 'feat: released a new version'
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add .
          git commit -m "${{env.CI_COMMIT_MESSAGE}}"
          git tag -a ${{steps.version}} head -m "chore: released vserion ${{steps.version}}"
          git push origin main
          git push --tags
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          tag: main
        run: |
          gh release create "${{steps.version}}" \
              --title="Released Artifact ${{steps.version}}" \
              --generate-notes \
              --verify-tag
              --draft
